# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Peizhuang Cong
email: congpeizhuang@bupt.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
  PhD student in the State Key Laboratory Of Networking And Switching Technology of Beijing University of Posts and Telecommunications.
  My research interests include the next generation network architecture and mobile Internet.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://congpeizhuang.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: 
#github_username:  congpeizhuang

# Build settings
theme: plainwhite
plugins:
  - jekyll-feed

plainwhite:
  # navigation:
  #   - title: About
  #     url: "/#posts-label-about"
  #   - title: News
  #     url: "/#posts-label"
  dark_mode: true
  tagline: |
    PhD Student
    Beijing University of Posts and Telecommunications, China
  name: Peizhuang Cong
  date_format: "%b %-d, %Y"
  sitemap: false

  #social_links:
    #twitter: andrew_gclark
    #github: andrewc19
    #linkedIn: in/andrewc19/ # format: locale/username

style: light
listen_for_clients_preferred_style: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
